### ISSUE TITLE
there're some useless service port

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#461]
1. install harbor with manifests/samples/full_stack_other_fs.yaml
2. check `kubectl get svc`
3. there're some useless porta exported, say harborcluster-sample-harbor-harbor-core:80
![image](https://user-images.githubusercontent.com/188115/109623752-6d00e800-7b78-11eb-8b9a-7e75deed0938.png)

**Comment by steven-zou** [comment]
@bitsf 

You mean the HTTP ports are useless as HTTPS ports have been exposed?

**Comment by steven-zou** [comment]
@holyhope 

Any comments for the `useless` ports?

**Comment by heww** [comment]
I had removed the useless service port of core/registry in this https://github.com/goharbor/harbor-operator/pull/525

**Comment by steven-zou** [comment]
Let's keep the network policy as it is now (redundant applying: all (80n and 443 open or all closed).

**Comment by holyhope** [comment]
Service expose all ports that _may be_ open.
Container expose only the expected ports.
This way service do not change when tls is enabled/disabled, and container is still secure since it does not expose unwanted port.
But IMO this is a bad feature and useless ports should be removed from `Service` (and `NetworkPolicy`) resources.
